version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0               #broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092   #if it doesn't work, try changing localhost to "kafka" or "broker". localhost is used when python in on windows and kafka ins on Docker (Linux).
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    # Retention settings go here
      KAFKA_LOG_RETENTION_HOURS: 300        # keep data for 7 days
      KAFKA_LOG_RETENTION_BYTES: -1         # unlimited size
      KAFKA_LOG_SEGMENT_BYTES: 1073741824   # 1GB segments
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
